server:
  port: 8084

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/orders}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
