server:
  port: 8083
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  application:
    name: auth-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
